package tipos;

public enum TiposBicicletas {
    BICICLETA_MONTANA,
    BICICLETA_URBANA,
    BICICLETA_RUTA,
    BICICLETA_PLEGABLES,
    BICICLETA_BMX,
    BICICLETA_HIBRIDA,
    BICICLETA_ELECTRICAS
}
